### ISSUE TITLE
French translation updated

### ISSUE THREAD

**Issue by samboowoo** [Pittvandewitt/Wavelet-strings#12]
Minor changements in french translation.
https://github.com/samboowoo/Wavelet-strings/blob/patch-1/values-fr/strings.xml

**Comment by Pittvandewitt** [comment]
Thank you for the update. It will be merged and pushed to this repo.

**Comment by samboowoo** [comment]
Hello Thomas,

I've updated to the last version, but one of the two minors change hasn't
been fixed ? ( one space before ':' )
https://github.com/samboowoo/Wavelet-strings/commit/3b14e9a3ab0313ba1d5bc5e43384d9d58d9dbd2c#diff-9983e2ce6960eb2184ec1e12544da2d494d6c2b47bcb19ca3773d3b34d908b73

Best regards,
Sam

**Comment by samboowoo** [comment]
Édit :
I've noticed also that there is a term "null" before  -connectė-  in
notifications not translated (not present in string file ?)
Could you check, please ?

Hello Thomas,

**Comment by samboowoo** [comment]
Hello Thomas,
Any answer about previous messages ?
Regards,
Sam

Le mar. 2 mars 2021 à 09:11, Samuel PINGUET ***@***.***> a
écrit :

**Comment by Pittvandewitt** [comment]
Hello,

The translation will be updated in the next release. The null term means that no device is found at all. This may be a bug, but not something that can be translated. Perhaps you want to create an issue for that and provide possible steps to reproduce the issue. It would be very useful if you can share some information such as Android version, what headphones you have currently connected etc: ttps://github.com/Pittvandewitt/Wavelet/issues
