### ISSUE TITLE
Austrian German Translations Are Not Standard But Dialect

### ISSUE THREAD

**Issue by Macusercom** [Pittvandewitt/Wavelet-strings#32]
Since the latest Wavelet update a German and Austrian translation has been added. Given that Austrian German isn't that different, the use of the German translation for Austrian German would be totally sufficient. There is no part in Wavelet that would require any special Austrian translation.

The current one seems to be in a heavy Viennese dialect that might be used colloquially, but has no standardised way of writing it nor is it proper standard German. The first time I've launched the updated Wavelet app I thought someone made serious grammar and spelling mistakes and I assume other people with their devices set to "German (Austria)" will feel the same way.

If anything, at least a language selector inside Wavelet would be enough but definitely more effort. My device is set to "German (Austria)" by default and I feel like it is really unnecessary having to switch to "German (Germany)" just to not see colloquial expressions in Wavelet. Other apps seem to either not use Austrian German specifically or use the German standard translation since I never had such translation issues despite using Austrian German as default on my device.

**Comment by Tiefseetauchner** [comment]
Wait what

They merged it?!

The PR is still open, I totally forgot abiut this...

**Comment by Macusercom** [comment]
Yes, they've merged it. I mean I find it hilarious, but only if it was optional. Right now it looks like a bad joke

**Comment by Macusercom** [comment]
EDIT: I've closed it by accident.

**Comment by Pittvandewitt** [comment]
As I interpret it now it is best to just remove this translation completely, is that right?

**Comment by Macusercom** [comment]
In my opinion it should be removed. It is in no way representative for Austrian German. I'm not sure if the system automatically uses the German translation though or if the German translation needs to be copied 1:1 for Austrian German. Either way, the German (Germany) translation is the proper one for all German speaking countries
